import assert from 'node:assert/strict';
import { readFile,readdir } from 'node:fs/promises';
import { build } from 'esbuild';
import { Miniflare } from 'miniflare';
import { hashPassword,verifyPassword } from '../lib/password.ts';
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB']});
try {
 const credentials=await hashPassword('SenhaSegura123!');
 assert.equal(await verifyPassword('SenhaSegura123!',credentials.hash,credentials.salt),true);
 assert.equal(await verifyPassword('SenhaErrada123!',credentials.hash,credentials.salt),false);
 const db=await mf.getD1Database('DB');
 for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql).run();
 const admin={id:'admin',email:'admin@test.test',name:'Admin',role:'admin',active:1,department:'Direção',access_scope:'all'};
 globalThis.testDb=db;globalThis.testMember=admin;
 const result=await build({entryPoints:['./app/api/workspace/route.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'test-service',setup(b){b.onResolve({filter:/^@\/lib\/service$/},()=>({path:'service',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export function database(){return globalThis.testDb;} export async function member(){return globalThis.testMember;} export function event(u,a,d){return database().prepare("INSERT INTO audit (actor,action,detail,created_at) VALUES (?,?,?,?)").bind(u.name,a,JSON.stringify(d),new Date().toISOString());}'}));}}]});
 const api=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
 await db.prepare('INSERT INTO users (id,email,name,role,created_at) VALUES (?,?,?,?,?)').bind(admin.id,admin.email,admin.name,admin.role,new Date().toISOString()).run();
 const post=async(body,origin='https://test.local')=>api.POST(new Request('https://test.local/api/workspace',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
 assert.equal((await post({action:'user',name:'Sem senha',email:'sem-senha@test.test',role:'employee',department:'Financeiro'})).status,400);
 assert.equal((await post({action:'user',name:'Alice',email:'alice@test.test',password:'AliceSenha123!',role:'employee',department:'Financeiro'})).status,200);
 assert.equal((await post({action:'user',name:'Bob',email:'bob@test.test',password:'BobSenha123!',role:'employee',department:'Compras'})).status,200);
 assert.equal((await post({action:'user',name:'Gestor Financeiro',email:'fin@test.test',password:'Financeiro123!',role:'manager',department:'Financeiro',accessScope:'own'})).status,200);
 assert.equal((await post({action:'user',name:'Gestor RH',email:'rh@test.test',password:'RecursosHumanos123!',role:'manager',department:'RH',accessScope:'all'})).status,200);
 const alice=await db.prepare('SELECT * FROM users WHERE email=?').bind('alice@test.test').first(),bob=await db.prepare('SELECT * FROM users WHERE email=?').bind('bob@test.test').first();
 assert.equal((await post({action:'create',title:'Entrega',employeeId:alice.id,due:'2026-10-01'})).status,200);
 assert.equal((await post({action:'create',title:'Compra',employeeId:bob.id,due:'2026-10-01'})).status,200);
 const task=await db.prepare('SELECT * FROM tasks').first();
 const financeManager=await db.prepare('SELECT * FROM users WHERE email=?').bind('fin@test.test').first(),hrManager=await db.prepare('SELECT * FROM users WHERE email=?').bind('rh@test.test').first();
 globalThis.testMember=financeManager;let scoped=await (await api.GET()).json();assert.equal(scoped.tasks.length,1);assert.ok(scoped.users.every(u=>u.department==='Financeiro'));assert.equal((await post({action:'create',title:'Bloqueada',employeeId:bob.id,due:'2026-10-01'})).status,400);
 globalThis.testMember=hrManager;scoped=await (await api.GET()).json();assert.equal(scoped.tasks.length,2);assert.ok(scoped.users.some(u=>u.department==='Compras'));
 globalThis.testMember=bob;assert.equal((await (await api.GET()).json()).tasks.length,1);assert.equal((await post({action:'edit',id:task.id,title:'Invadida'})).status,403);
 globalThis.testMember=alice;assert.equal((await post({action:'user',name:'Alice',email:alice.email,role:'manager',department:'Financeiro'})).status,403);assert.equal((await post({action:'review',id:task.id,score:5})).status,400);
 assert.equal((await post({action:'edit',id:task.id,title:'Relatório final',notes:'Finalizado'})).status,200);assert.equal((await post({action:'complete',id:task.id})).status,200);
 assert.equal((await post({action:'submit',title:'Conferência diária',notes:'Pagamentos conferidos e enviados.'})).status,200);
 globalThis.testMember=financeManager;const managerAfterSubmission=await (await api.GET()).json();assert.equal(managerAfterSubmission.tasks.length,2);assert.ok(managerAfterSubmission.tasks.some(t=>t.title==='Conferência diária'&&t.status==='completed'&&t.created_by===alice.id));
 globalThis.testMember=alice;
 let data=await (await api.GET()).json();assert.equal(data.users.length,1);assert.equal(data.history.length,0);
 globalThis.testMember=admin;data=await (await api.GET()).json();const edited=data.tasks.find(t=>t.id===task.id);assert.equal(edited.title,'Relatório final');assert.equal(edited.completion_notes,'Finalizado');assert.equal(edited.status,'completed');assert.ok(data.history.some(h=>h.action==='Atividade editada'));
 assert.equal((await post({action:'goal',title:'Entregas',employeeId:alice.id,due:'2026-10-01',target:3})).status,200);
 assert.equal((await post({action:'complete',id:task.id},'https://evil.test')).status,403);
 globalThis.testMember=null;assert.equal((await api.GET()).status,401);
 console.log('PASS: migrations, password hashing, sector isolation, HR all-sector access, employee submission, manager receipt, denied escalation, persistent edits, completion, goals, audit, CSRF and anonymous denial.');
}finally{await mf.dispose();}
