'use client';
import { useCallback,useEffect,useState } from 'react';
import { Activity,BarChart3,Check,History,KeyRound,ListChecks,LockKeyhole,LogOut,Medal,RefreshCw,ShieldCheck,Target,Trophy,UserCog,UserPlus,Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect,NativeSelectOption } from '@/components/ui/native-select';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { productivityScore } from '@/lib/ranking';

type Person={id:string;name:string;email:string;role:string;active:number};
type Task={id:number;title:string;employee_id:string;employee_name:string;due_date:string;status:string;completion_notes:string;completed_at:string|null;created_at:string;proactivity:number|null;comment:string|null};
type Goal={id:number;title:string;employee_id:string;employee_name:string;target:number;due_date:string;created_at:string};
type Data={me:Person;users:Person[];tasks:Task[];goals:Goal[];history:{id:number;actor:string;action:string;detail:string;created_at:string}[]};
const roles:Record<string,string>={admin:'Administrador',manager:'Gestor',employee:'Funcionário'};
const statuses:Record<string,string>={pending:'Pendente',in_progress:'Em andamento',completed:'Aguardando avaliação',reviewed:'Avaliada'};
const done=(t:Task)=>t.status==='completed'||t.status==='reviewed';
type Rank={person:Person;total:number;completed:number;onTime:number;rating:number|null;score:number};
function makeRanking(users:Person[],tasks:Task[]):Rank[]{
 return users.filter(p=>p.role==='employee'&&p.active).map(person=>{
  const own=tasks.filter(t=>t.employee_id===person.id),finished=own.filter(done),rated=own.filter(t=>t.proactivity!==null);
  const onTime=finished.filter(t=>t.completed_at&&t.completed_at.slice(0,10)<=t.due_date).length;
  const {rating,score}=productivityScore(own.length,finished.length,onTime,rated.map(t=>t.proactivity!));
  return {person,total:own.length,completed:finished.length,onTime,rating,score};
 }).sort((a,b)=>b.score-a.score||b.completed-a.completed||a.person.name.localeCompare(b.person.name));
}

export default function Dashboard(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('overview'),[modal,setModal]=useState(''),[selected,setSelected]=useState<Task|null>(null),[selectedUser,setSelectedUser]=useState<Person|null>(null),[checking,setChecking]=useState(true);
 const reload=useCallback(async()=>{const response=await fetch('/api/workspace',{cache:'no-store'});const result=await response.json() as Data & {error?:string};if(!response.ok){if(response.status===401)setData(null);throw Error(result.error);}setData(result);setError('');},[]);
 useEffect(()=>{const refresh=()=>{void reload().catch(()=>undefined).finally(()=>setChecking(false));};refresh();const id=setInterval(refresh,15000);return()=>clearInterval(id);},[reload]);
 useEffect(()=>{if(data?.me.role==='employee'&&['overview','history','team','ranking'].includes(view))setView('tasks');},[data,view]);
 useEffect(()=>{
  if(!data)return;
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController(),register=(tool:unknown)=>Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);
  if(data.me.role!=='employee')void register({name:'read_team_ranking',title:'Consultar ranking da equipe',description:'Retorna o ranking atual de produtividade dos funcionários, disponível somente para gestores.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return {ranking:makeRanking(data.users,data.tasks).map((row,index)=>({position:index+1,name:row.person.name,score:row.score,completed:row.completed,total:row.total,onTime:row.onTime,rating:row.rating}))};}});
  if(data.me.role==='admin')void register({name:'create_team_user',title:'Cadastrar usuário',description:'Cadastra um usuário e define seu perfil como gestor ou funcionário.',inputSchema:{type:'object',properties:{name:{type:'string'},email:{type:'string'},password:{type:'string',minLength:10},role:{type:'string',enum:['manager','employee']}},required:['name','email','password','role'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const value=input as {name?:string;email?:string;password?:string;role?:string};if(!value.name?.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.email||'')||!value.password||value.password.length<10||!['manager','employee'].includes(value.role||''))throw Error('Informe nome, e-mail, senha e perfil válidos.');const response=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'user',name:value.name.trim(),email:value.email!.trim(),password:value.password,role:value.role,active:true})});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error||'Não foi possível cadastrar.');await reload();return {saved:true,email:value.email,role:value.role};}});
  return()=>lifecycle.abort();
 },[data,reload]);
 async function save(body:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json() as {error?:string;forceLogout?:boolean};if(!r.ok)throw Error(result.error);if(result.forceLogout){setData(null);setModal('');setNotice('Senha alterada. Entre novamente.');return;}await reload();setModal('');setNotice('Alteração salva.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function submit(event:React.FormEvent<HTMLFormElement>,action:string){event.preventDefault();const f=Object.fromEntries(new FormData(event.currentTarget));void save({...f,action,id:selected?.id,active:f.active!=='0'});}
 async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);setChecking(false);}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});setData(null);setNotice('');setError('');}
 if(!data)return <Login onSubmit={login} busy={busy} error={error} checking={checking} notice={notice}/>;
 const manager=data.me.role!=='employee',admin=data.me.role==='admin',employees=data.users.filter(p=>p.role==='employee'&&p.active),completed=data.tasks.filter(done),ratings=data.tasks.filter(t=>t.proactivity!==null),average=ratings.length?(ratings.reduce((sum,t)=>sum+t.proactivity!,0)/ratings.length).toFixed(1):'—',ranking=manager?makeRanking(data.users,data.tasks):[];
 const titles:Record<string,string>={overview:'Visão geral',tasks:manager?'Atividades da equipe':'Minhas atividades',goals:'Metas',ranking:'Ranking de produtividade',history:'Histórico de alterações',team:'Equipe e acessos'};
 const navigation=[...(manager?[['overview','Visão geral',BarChart3],['ranking','Ranking',Trophy]]:[]),['tasks','Atividades',ListChecks],['goals','Metas',Target],...(manager?[['history','Histórico',History],['team','Equipe',Users]]:[])];
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Check/></span>Avança</div><nav>{navigation.map(([key,label,Icon])=><button key={key as string} className={'nav-item '+(view===key?'active':'')} onClick={()=>setView(key as string)}><Icon size={18}/>{label as string}</button>)}</nav><div className="profile-card"><div><strong>{data.me.name}</strong><span>{roles[data.me.role]}</span></div></div></aside><section className="workspace"><header className="topbar"><span className="access-badge"><ShieldCheck size={16}/>{roles[data.me.role]}</span><div className="top-actions"><Button variant="ghost" onClick={()=>setModal('password')}><KeyRound/> Alterar senha</Button><Button variant="ghost" onClick={()=>void reload().catch(e=>setError(e.message))}><RefreshCw/> Atualizar</Button><button className="logout-button" onClick={()=>void logout()}><LogOut/> Sair</button></div></header><div className="page-content"><div className="page-heading"><div><p className="eyebrow">SEU ESPAÇO DE TRABALHO</p><h1>{titles[view]}</h1><p>Olá, {data.me.name}. Os dados são atualizados a cada 15 segundos.</p></div>{manager&&view==='tasks'&&<Button onClick={()=>setModal('create')}>Nova atividade</Button>}{manager&&view==='goals'&&<Button onClick={()=>setModal('goal')}>Nova meta</Button>}{admin&&view==='team'&&<Button onClick={()=>{setSelectedUser(null);setModal('user')}}><UserPlus/> Cadastrar usuário</Button>}</div>{error&&<p className="feedback-error" role="alert">{error}</p>}{notice&&<p className="feedback-success" role="status">{notice}</p>}
 <div className="stats-grid"><article className="stat-card"><div><span>Concluídas</span><strong>{completed.length}</strong></div></article><article className="stat-card"><div><span>Aguardando avaliação</span><strong>{data.tasks.filter(t=>t.status==='completed').length}</strong></div></article><article className="stat-card"><div><span>Proatividade média (1 a 5)</span><strong>{average}</strong></div></article></div>
 {view==='overview'&&manager&&<ManagerOverview tasks={data.tasks} ranking={ranking} onRanking={()=>setView('ranking')}/>} 
 {view==='ranking'&&manager&&<Ranking ranking={ranking}/>} 
 {view==='tasks'&&<section className="panel tasks-panel">{!data.tasks.length&&<p>Nenhuma atividade cadastrada ainda.</p>}{data.tasks.map(t=><article className="task-row" key={t.id}><span>{done(t)?'✓':'○'}</span><div className="task-main"><strong>{t.title}</strong><p>{t.employee_name} · Prazo: {t.due_date.split('-').reverse().join('/')}</p><span>{statuses[t.status]}</span>{t.completion_notes&&<p className="record-text">{t.completion_notes}</p>}{t.proactivity!==null&&<p>Proatividade: {t.proactivity}/5 — {t.comment||'Sem comentário'}</p>}</div><div className="task-actions"><Button variant="outline" onClick={()=>{setSelected(t);setModal('edit');}}>Editar</Button>{!done(t)&&<Button disabled={busy} onClick={()=>void save({action:'complete',id:t.id})}>Concluir</Button>}{manager&&done(t)&&<Button onClick={()=>{setSelected(t);setModal('review');}}>Avaliar</Button>}</div></article>)}</section>}
 {view==='goals'&&<section className="panel tasks-panel">{!data.goals.length&&<p>Nenhuma meta definida ainda.</p>}{data.goals.map(g=>{const count=completed.filter(t=>t.employee_id===g.employee_id&&t.completed_at&&t.completed_at>=g.created_at&&t.completed_at.slice(0,10)<=g.due_date).length;return <article className="goal-item" key={g.id}><h2>{g.title}</h2><p>{g.employee_name} · Até {g.due_date.split('-').reverse().join('/')}</p><Progress value={Math.min(100,count/g.target*100)}/><p>{count} de {g.target} atividades concluídas desde a criação da meta e até o prazo.</p></article>;})}</section>}
 {view==='history'&&manager&&<section className="panel tasks-panel"><p>Últimos 200 registros, incluindo os valores anteriores e novos.</p>{!data.history.length&&<p>O histórico aparecerá conforme a equipe usar o sistema.</p>}{data.history.map(h=><article className="history-item" key={h.id}><strong>{h.actor} · {h.action}</strong><p>{new Date(h.created_at).toLocaleString('pt-BR')}</p><pre>{JSON.stringify(JSON.parse(h.detail),null,2)}</pre></article>)}</section>}
 {view==='team'&&manager&&<section className="panel tasks-panel">{admin&&<p>Cadastre cada pessoa com e-mail, senha e perfil. Você pode adicionar quantos usuários precisar e alterar os acessos depois.</p>}{data.users.map(p=>{const total=data.tasks.filter(t=>t.employee_id===p.id).length,count=completed.filter(t=>t.employee_id===p.id).length;return <article className="member-row" key={p.id}><div className="member-avatar">{p.name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()}</div><div><h2>{p.name}</h2><p>{p.email} · <span className={'role-chip '+p.role}>{roles[p.role]}</span> · {p.active?'Ativo':'Desativado'}</p><Progress value={total?count/total*100:0}/><small>{count} de {total} atividades concluídas</small></div>{admin&&p.role!=='admin'&&<Button variant="outline" onClick={()=>{setSelectedUser(p);setModal('user')}}>Editar acesso</Button>}</article>;})}</section>}
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('');}}><DialogContent><DialogHeader><DialogTitle>{modal==='user'?'Cadastrar ou atualizar usuário':modal==='password'?'Alterar minha senha':modal==='edit'?'Editar atividade':modal==='review'?'Avaliar proatividade':modal==='goal'?'Definir meta':'Nova atividade'}</DialogTitle></DialogHeader><form className="form-stack" onSubmit={e=>submit(e,modal==='password'?'change_password':modal)} key={modal+selected?.id}>
 {modal==='user'?<><label>Nome<Input name="name" required maxLength={300} defaultValue={selectedUser?.name}/></label><label>E-mail de acesso<Input name="email" type="email" required defaultValue={selectedUser?.email}/></label><label>{selectedUser?'Nova senha (deixe vazia para manter)':'Senha inicial'}<Input name="password" type="password" minLength={10} maxLength={200} required={!selectedUser} autoComplete="new-password"/></label><p className="field-help">Use pelo menos 10 caracteres.</p><label>Perfil<NativeSelect name="role" defaultValue={selectedUser?.role||'employee'}><NativeSelectOption value="employee">Funcionário</NativeSelectOption><NativeSelectOption value="manager">Gestor</NativeSelectOption></NativeSelect></label><label>Acesso<NativeSelect name="active" defaultValue={selectedUser?.active===0?'0':'1'}><NativeSelectOption value="1">Ativo</NativeSelectOption><NativeSelectOption value="0">Desativado</NativeSelectOption></NativeSelect></label></>:modal==='password'?<><label>Nova senha<Input name="password" type="password" minLength={10} maxLength={200} required autoComplete="new-password"/></label><p className="field-help">Depois de salvar, entre novamente com a nova senha.</p></>:modal==='review'?<><label>Nota de proatividade (1 a 5)<Input name="score" type="number" min="1" max="5" required defaultValue={selected?.proactivity||3}/></label><label>Feedback<Textarea name="comment" maxLength={5000} defaultValue={selected?.comment||''}/></label></>:<><label>Nome {modal==='goal'?'da meta':'da atividade'}<Input name="title" required maxLength={300} defaultValue={modal==='edit'?selected?.title:''}/></label>{modal==='edit'?<label>Registro do trabalho<Textarea name="notes" maxLength={5000} defaultValue={selected?.completion_notes}/></label>:<><label>Funcionário<NativeSelect name="employeeId" required><NativeSelectOption value="">Selecione</NativeSelectOption>{employees.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect></label><label>Prazo<Input type="date" name="due" required/></label>{modal==='goal'&&<label>Quantidade de atividades<Input name="target" type="number" min="1" required/></label>}</>}</>}
 {error&&<p role="alert" className="feedback-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Salvando…':'Salvar'}</Button></form></DialogContent></Dialog>
 </div></section></main>;
}

function Login({onSubmit,busy,error,checking,notice}:{onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void;busy:boolean;error:string;checking:boolean;notice:string}){
 return <main className="login-page"><section className="login-card"><div className="login-brand"><span className="brand-mark"><Check/></span>Avança</div><div className="login-copy"><p className="eyebrow">ACESSO INDIVIDUAL</p><h1>Entre no seu espaço</h1><p>Use o e-mail e a senha cadastrados pelo administrador.</p></div><form className="login-form" onSubmit={onSubmit}><label>E-mail<Input name="email" type="email" required autoComplete="username" placeholder="voce@empresa.com"/></label><label>Senha<Input name="password" type="password" required autoComplete="current-password" placeholder="Sua senha"/></label>{error&&<p className="feedback-error" role="alert">{error}</p>}{notice&&<p className="feedback-success" role="status">{notice}</p>}<Button type="submit" disabled={busy||checking}><LockKeyhole/>{busy?'Entrando…':checking?'Verificando…':'Entrar'}</Button></form><div className="login-security"><ShieldCheck/><div><strong>Acesso protegido</strong><span>Gestores veem gráficos e ranking. Funcionários veem somente o próprio trabalho.</span></div></div></section><aside className="login-side"><div><span className="side-kicker">GESTÃO DE DESEMPENHO</span><h2>Uma conta para cada pessoa.<br/>A visão certa para cada função.</h2><div className="login-feature"><UserCog/><span><strong>Perfis definidos pelo administrador</strong><small>Gestor ou funcionário, com permissões separadas.</small></span></div></div></aside></main>;
}

function ManagerOverview({tasks,ranking,onRanking}:{tasks:Task[];ranking:Rank[];onRanking:()=>void}){
 const finished=tasks.filter(done),pending=tasks.filter(t=>!done(t));
 const late=pending.filter(t=>t.due_date<new Date().toISOString().slice(0,10)).length;
 const max=Math.max(1,...ranking.map(r=>r.total));
 const week=Array.from({length:7},(_,offset)=>{const date=new Date();date.setDate(date.getDate()-(6-offset));const key=date.toISOString().slice(0,10);return {label:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][date.getDay()],count:finished.filter(t=>t.completed_at?.slice(0,10)===key).length};});
 const weekMax=Math.max(1,...week.map(d=>d.count));
 return <div className="manager-overview">
  <section className="panel chart-card"><div className="panel-title"><div><h2>Entregas nos últimos 7 dias</h2><p>Atualizado conforme os funcionários concluem atividades</p></div><Activity/></div><div className="week-chart" role="img" aria-label="Gráfico de atividades concluídas por dia">{week.map(day=><div key={day.label}><span>{day.count}</span><i style={{height:`${Math.max(6,day.count/weekMax*100)}%`}}/><small>{day.label}</small></div>)}</div></section>
  <section className="panel chart-card"><div className="panel-title"><div><h2>Produtividade por funcionário</h2><p>Atividades atribuídas e concluídas</p></div><BarChart3/></div><div className="people-bars">{ranking.map(row=><div key={row.person.id}><span>{row.person.name}</span><div><i style={{width:`${row.total/max*100}%`}}/><b style={{width:`${row.completed/max*100}%`}}/></div><strong>{row.completed}/{row.total}</strong></div>)}{!ranking.length&&<p>Cadastre funcionários para começar.</p>}</div></section>
  <section className="panel status-card"><div className="panel-title"><div><h2>Situação das atividades</h2><p>Visão geral da equipe</p></div></div><div className="status-body"><div className="donut" style={{background:`conic-gradient(#2e7568 0 ${tasks.length?finished.length/tasks.length*100:0}%,#e5ad42 0 ${tasks.length?(finished.length+pending.length-late)/tasks.length*100:0}%,#d35f69 0)`}}><span>{tasks.length}<small>Total</small></span></div><ul><li><i className="green"/>Concluídas <b>{finished.length}</b></li><li><i className="gold"/>Em andamento <b>{Math.max(0,pending.length-late)}</b></li><li><i className="red"/>Atrasadas <b>{late}</b></li></ul></div></section>
  <section className="panel podium-card"><div className="panel-title"><div><h2>Destaques da equipe</h2><p>Ranking pelo índice de produtividade</p></div><button onClick={onRanking}>Ver ranking completo</button></div><div className="podium-list">{ranking.slice(0,3).map((row,index)=><div key={row.person.id}><span className={`rank-number place-${index+1}`}>{index===0?<Trophy/>:<Medal/>}</span><div><strong>{row.person.name}</strong><small>{row.completed} entregas · {row.rating?.toFixed(1)||'—'} de proatividade</small></div><b>{row.score} pts</b></div>)}{!ranking.length&&<p>O ranking aparecerá após cadastrar funcionários.</p>}</div></section>
 </div>;
}

function Ranking({ranking}:{ranking:Rank[]}){
 return <section className="panel ranking-panel"><div className="ranking-explain"><Trophy/><div><h2>Índice de produtividade</h2><p>50% conclusão das atividades, 20% entregas no prazo e 30% avaliação de proatividade. Sem atividade ou avaliação, a pessoa não recebe pontos naquele critério.</p></div></div><div className="ranking-table"><div className="ranking-row ranking-head"><span>Posição</span><span>Funcionário</span><span>Entregas</span><span>No prazo</span><span>Proatividade</span><span>Pontuação</span></div>{ranking.map((row,index)=><div className="ranking-row" key={row.person.id}><span className="position">{index+1}º</span><strong>{row.person.name}</strong><span>{row.completed}/{row.total}</span><span>{row.onTime}/{row.completed}</span><span>{row.rating?.toFixed(1)||'—'}/5</span><b>{row.score} pts</b></div>)}{!ranking.length&&<p className="empty-ranking">Cadastre funcionários e atribua atividades para formar o ranking.</p>}</div></section>;
}
